CREATE TABLE IF NOT EXISTS `file_metadata` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `storage_id` varchar(500) NOT NULL COMMENT '存储ID（driver:storage@filename）',
    `original_filename` varchar(255) NOT NULL,
    `stored_filename` varchar(255) NOT NULL,
    `file_path` varchar(500) NOT NULL,
    `url` varchar(500) DEFAULT NULL,
    `file_size` bigint NOT NULL,
    `content_type` varchar(100) NOT NULL,
    `driver` varchar(50) NOT NULL,
    `visibility` varchar(10) NOT NULL DEFAULT 'pub',
    `category` varchar(50) DEFAULT NULL,
    `business_id` varchar(100) DEFAULT NULL,
    `business_type` varchar(50) DEFAULT NULL,
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_storage_id` (`storage_id`),
    KEY `idx_file_path` (`file_path`),
    KEY `idx_visibility` (`visibility`),
    KEY `idx_category` (`category`),
    KEY `idx_business_type` (`business_type`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
